#!/usr/bin/env bash
#
# bootstrap installs things.

# cd "$(dirname "$0")/.."
# DOTFILES_ROOT=$(pwd -P)
DOTFILES_ROOT="$(cd "$(dirname "$BASH_SOURCE")"; cd ..; pwd)"
# echo $DOTFILES_ROOT

set -e

function link_file() {
	local src=$1 dst=$2

	local overwrite= backup= skip= action=

	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then

		if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then

			local currentSrc="$(readlink $dst)"

			if [ "$currentSrc" == "$src" ]; then
				skip=true;
			else
				ask_input "File already exists: $dst ($(basename "$src")), what do you want to do:\n\t[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?" action

				case "$action" in
					o )
					overwrite=true;;
					O )
					overwrite_all=true;;
					b )
					backup=true;;
					B )
					backup_all=true;;
					s )
					skip=true;;
					S )
					skip_all=true;;
					* )
					;;
				esac

			fi

		fi

		overwrite=${overwrite:-$overwrite_all}
		backup=${backup:-$backup_all}
		skip=${skip:-$skip_all}

		if [ "$overwrite" == "true" ]; then
			rm -rf "$dst"
			print_success "removed $dst"
		fi

		if [ "$backup" == "true" ]; then
			mv "$dst" "${dst}.backup"
			print_success "moved $dst to ${dst}.backup"
		fi

		if [ "$skip" == "true" ]; then
			print_success "skipped $src"
		fi
	fi

	if [ "$skip" != "true" ]; then  # "false" or empty
		ln -s "$1" "$2"
		print_success "linked $1 to $2"
	fi
}

function install_dotfiles() {
	print_info 'Installing dotfiles'

	local overwrite_all=false backup_all=false skip_all=false

	for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
		echo 'found src'
		echo $src
		dst="$HOME/.$(basename "${src%.*}")"
		echo $dst
		# link_file "$src" "$dst"
	done
}


# If we're on a Mac, let's install and setup homebrew.
# if [ "$(uname -s)" == "Darwin" ]
# then
# print_info "installing dependencies"
# if source bin/dot > /tmp/dotfiles-dot 2>&1
# then
#   print_success "dependencies installed"
# else
#   print_error "error installing dependencies"
# fi
# fi


function main() {
	install_dotfiles
}

if [ "${1}" != "--source-only" ]; then
	main "${@}"
fi
